config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  mount ActionCable.server => '/cable'

  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"


  get 'signin', to: "sessions#new"
  post '/signin', to: "sessions#create" 
  delete '/signout', to: "sessions#destroy"


  resources :messages
  resources :halls, param: :permalink
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hall.rb
class Hall < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages

  validates :name, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :urlify

  # Naieve friendly url implementation
  def to_param
    self.permalink
  end

  def urlify
    self.permalink = self.name.downcase.gsub(" ", "-") unless self.name.nil?
  end

  def sanitize
    self.name = self.name.strip unless self.name.nil?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :hall
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :halls, through: :messages

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !!current_user #negating the value to boolean
  end

  protected
  def authenticate_user!
    redirect_to root_path unless signed_in?
  end
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  before_action :authenticate_user!

  def index
    @halls = Hall.all
    @hall = Hall.new
  end

  def new
    @hall = Hall.new
  end

  def create
    @hall = Hall.new(hall_params)
    if @hall.save
      respond_to do |format|
        format.html { redirect_to @hall }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chathall with this name already exists"]}
        format.html { redirect_to new_hall_path }
        format.js { render template: 'halls/hall_errors.js.erb'}
      end
    end
  end

  def edit
    @hall = Hall.find_by(permalink: params[:permalink])
  end

  def update
    @hall = Hall.find_by(permalink: params[:permalink])
    @hall.update(hall_params)
    redirect_to @hall
  end


  def show
    @hall = Hall.find_by(permalink: params[:permalink])
    # Iniating messages creation in the hall.
    @message = Message.new
  end

  private

  def hall_params
    params.require(:hall).permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    @message.user = current_user

    if @message.save
      ActionCable.server.broadcast 'messages',
                                   message: @message,
                                   user: @message.user.username,
                                   time: @message.created_at.strftime("at %I:%M%p ")
      head :ok
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :hall_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @user =  User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to halls_path
    else
      redirect_to signup_path, flash[:notice] = @user.errors.messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    user = User.find_by(user_params)
    if user
      session[:user_id] = user.id
      redirect_to halls_path
    else
      redirect_to signin_path, flash[:notice] =  {username: ["doesn't exist"]}
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/halls/_hall.html.erb
<li><%= link_to hall.name, hall_path(hall) %></li>

app/views/halls/_hall_form.html.erb
<div class="chathall-form">
  <%= form_for hall, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">Hall Name:</span>
      <%= f.text_field :name, class: "form-control"%>
    </div><br />
    <%= f.submit class: "btn btn-primary", id: "create-hall" %>
  <% end %>
</div>

app/views/halls/create.js.erb
$("input#hall_name").val(" ")
$("#hall-errors").html(" ")
$("#hall-index").append('<li><%= link_to @hall.name, hall_path(@hall) %></li>')

app/views/halls/hall_errors.js.erb
$("input#hall_name").val(" ");
$("#hall-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/halls/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatrooms">
  <%= render partial: 'hall_form', locals: {hall: @hall} %>
  <div id="hall-errors">

  </div>
  <hr />
</div>

<div class="row col-md-8 col-md-offset-2">
  <h2>Chat Halls</h2>

  <ul id="hall-index">
  <% if @halls.any? %>
      <%= render @halls %>
  <%else %>
    </ul>
    <p>No chat halls here, create the first one!</p>
  <% end %>
</div>

app/views/halls/new.html.erb
<div class="jumbotron">
  <h2>Create a Chat Hall </h2>
  <%= form_for @hall do |f| %>
    <div class="input-group">
      <span class="input-group-addon">name:</span>
      <%= f.text_field :name, class: "form-control"%>
    </div><br />
    <%= f.submit class: "btn btn-primary", id: "create-chathall" %>
  <% end %>

  <%= render partial: 'layouts/flash_errors'%>
</div>

app/views/halls/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @hall.name %></h1>

  <div class="panel panel-default">
    <% if @hall.messages.any? %>
      <div class="panel-body" id="messages">
        <%= render partial: 'messages/message', collection: @hall.messages %>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>

  <%= render partial: 'messages/message_form', locals: {message: @message, hall: @hall}%><br />
</div>

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
 <div class="header clearfix">
   <nav>
     <ul class="nav nav-pills pull-xs-right">
       <% if current_user %>
         <li class="nav-item">
           <%= link_to "New chat hall", new_hall_path, class: "nav-link" %>
        </li>
       <% end %>
       <li class="nav-item">
         <%= link_to "Halls", halls_path, class: "nav-link" %>
       </li>
       <% if current_user %>
         <li class="nav-item">
           <%= link_to "Sign Out", signout_path, method: "delete", class: "nav-link" %>
         </li>
       <% else %>
         <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "nav-link" %></li>
         <li class="nav-item"><%= link_to "Sign In", signin_path, class: "nav-link" %></li>
       <% end %>

     </ul>
   </nav>
   <h3 class="text-muted">
     <%= link_to 'Expert Potato', root_path %>
   </h3>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpertPotato</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'layouts/navbar' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<p><small><%= message.created_at.strftime("at %I:%M%p ")%></small>:<strong><%=message.user.username%>:</strong> <%=message.content%></p>

app/views/messages/_message_form.html.erb
<%=form_for message, remote: true, authenticity_token: true do |f|%>
  <%= f.label :your_message %>:
  <%= f.text_area :content, class: "form-control", data: {textarea: "message"}%>

  <%= f.hidden_field :hall_id, value: hall.id %>
  <%= f.submit "send", class: "btn btn-primary", style: "display: none", data: {send: "message"}%>
<%end%>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Expert Potato</h1>
  <h3>the messing chatt app!</h3>
  <%if current_user%>
    <p><span class="glyphicon glyphicon-heart"></span> Nice to see you, <%= current_user.username%> <span class="glyphicon glyphicon-heart"></span></p>
    <%= link_to 'New chat Hall', new_hall_path, class: "btn btn-lg btn-success" %>
  <% else %>
    <p class="lead">Please, sign in to start creating halls and chatting with another humans..</p>
    <%= link_to 'Sign in', signin_path, class: "btn btn-lg btn-success" %>
    <p class="lead">Or, sign up if you wish..</p>
    <%= link_to 'Sign up', signup_path, class: "btn btn-lg btn-warning" %>
  <%end%>
</div>